import { PrismaClient } from "@prisma/client"

const prisma = new PrismaClient()

async function main() {
  console.log("🌱 Seeding database...")

  // --- Agent ---
  const agent = await prisma.user.upsert({
    where: { email: "agent@homematch.dev" },
    update: {},
    create: {
      email: "agent@homematch.dev",
      name: "Victor (Agent)",
      role: "AGENT",
      phone: "555-000-0001",
    },
  })
  console.log(`  ✓ Agent: ${agent.name} (${agent.id})`)

  // --- Buyers ---
  const buyer1 = await prisma.user.upsert({
    where: { email: "buyer1@homematch.dev" },
    update: {},
    create: {
      email: "buyer1@homematch.dev",
      name: "Sarah Chen",
      role: "BUYER",
      phone: "555-000-0002",
    },
  })

  const buyer2 = await prisma.user.upsert({
    where: { email: "buyer2@homematch.dev" },
    update: {},
    create: {
      email: "buyer2@homematch.dev",
      name: "Marcus Johnson",
      role: "BUYER",
      phone: "555-000-0003",
    },
  })

  // --- Buyer Profiles ---
  const bp1 = await prisma.buyerProfile.upsert({
    where: { userId: buyer1.id },
    update: {},
    create: {
      userId: buyer1.id,
      agentId: agent.id,
      status: "ACTIVE",
      budgetMin: 450000,
      budgetMax: 650000,
      minBedrooms: 3,
      minBathrooms: 2,
      propertyTypes: ["SFH", "TOWNHOUSE"],
      targetCities: ["Seattle", "Bellevue"],
      targetZipCodes: ["98103", "98105", "98115"],
      mustHaves: ["natural_light", "home_office_count"],
      dealBreakers: ["noise_level"],
    },
  })

  const bp2 = await prisma.buyerProfile.upsert({
    where: { userId: buyer2.id },
    update: {},
    create: {
      userId: buyer2.id,
      agentId: agent.id,
      status: "ACTIVE",
      budgetMin: 350000,
      budgetMax: 500000,
      minBedrooms: 2,
      minBathrooms: 1,
      propertyTypes: ["CONDO", "TOWNHOUSE"],
      targetCities: ["Seattle"],
      targetZipCodes: ["98101", "98102", "98109"],
      mustHaves: ["walk_score", "commute_minutes_primary"],
      dealBreakers: [],
    },
  })

  console.log(`  ✓ Buyer: ${buyer1.name} (${bp1.id})`)
  console.log(`  ✓ Buyer: ${buyer2.name} (${bp2.id})`)

  // --- Listings (8 with realistic vectors) ---
  const listings = [
    {
      address: "2415 NE 65th St",
      city: "Seattle",
      state: "WA",
      zipCode: "98115",
      listPrice: 575000,
      propertyType: "SFH" as const,
      bedrooms: 3,
      bathroomsFull: 2,
      bathroomsHalf: 0,
      interiorSqft: 1650,
      lotSqft: 4800,
      yearBuilt: 1942,
      vector: {
        price: 575000,
        price_per_sqft: 348,
        bedrooms: 3,
        bathrooms: 2,
        interior_sqft: 1650,
        lot_sqft: 4800,
        year_built: 1942,
        walk_score: 82,
        commute_minutes_primary: 22,
        school_rating: 7,
        noise_level: 4,
        street_type: "quiet_residential",
        roof_age_years: 8,
        hvac_age_years: 12,
        has_solar: false,
        heating_type: "gas",
        openness: 3,
        kitchen_layout: "l_shape",
        has_dining_room: true,
        home_office_count: 1,
        storage_abundance: 3,
        ceiling_height_feet: 8,
        natural_light: 4,
        view_quality: 2,
        privacy_from_neighbors: 3,
        finish_quality: "mid",
        move_in_readiness: 4,
        yard_size_category: "medium",
        yard_usability: 4,
        is_fenced: true,
        has_outdoor_space: true,
        vibe: "quiet",
        street_parking_ease: 3,
        commute_weighted_score: null,
        stretch_pct: null,
      },
    },
    {
      address: "1847 14th Ave",
      city: "Seattle",
      state: "WA",
      zipCode: "98122",
      listPrice: 489000,
      propertyType: "TOWNHOUSE" as const,
      bedrooms: 3,
      bathroomsFull: 2,
      bathroomsHalf: 1,
      interiorSqft: 1420,
      lotSqft: 1200,
      yearBuilt: 2018,
      vector: {
        price: 489000,
        price_per_sqft: 344,
        bedrooms: 3,
        bathrooms: 2.5,
        interior_sqft: 1420,
        lot_sqft: 1200,
        year_built: 2018,
        walk_score: 91,
        commute_minutes_primary: 15,
        school_rating: 6,
        noise_level: 2,
        street_type: "busy_residential",
        roof_age_years: 6,
        hvac_age_years: 6,
        has_solar: false,
        heating_type: "electric",
        openness: 4,
        kitchen_layout: "island",
        has_dining_room: false,
        home_office_count: 1,
        storage_abundance: 2,
        ceiling_height_feet: 9,
        natural_light: 5,
        view_quality: 3,
        privacy_from_neighbors: 2,
        finish_quality: "high_end",
        move_in_readiness: 5,
        yard_size_category: "small",
        yard_usability: 2,
        is_fenced: false,
        has_outdoor_space: true,
        vibe: "lively",
        street_parking_ease: 2,
        commute_weighted_score: null,
        stretch_pct: null,
      },
    },
    {
      address: "7832 Ravenna Ave NE",
      city: "Seattle",
      state: "WA",
      zipCode: "98115",
      listPrice: 625000,
      propertyType: "SFH" as const,
      bedrooms: 4,
      bathroomsFull: 2,
      bathroomsHalf: 0,
      interiorSqft: 2100,
      lotSqft: 6200,
      yearBuilt: 1955,
      vector: {
        price: 625000,
        price_per_sqft: 298,
        bedrooms: 4,
        bathrooms: 2,
        interior_sqft: 2100,
        lot_sqft: 6200,
        year_built: 1955,
        walk_score: 75,
        commute_minutes_primary: 28,
        school_rating: 8,
        noise_level: 5,
        street_type: "quiet_residential",
        roof_age_years: 3,
        hvac_age_years: 5,
        has_solar: true,
        heating_type: "heat_pump",
        openness: 2,
        kitchen_layout: "u_shape",
        has_dining_room: true,
        home_office_count: 2,
        storage_abundance: 4,
        ceiling_height_feet: 8,
        natural_light: 3,
        view_quality: 2,
        privacy_from_neighbors: 5,
        finish_quality: "mid",
        move_in_readiness: 3,
        yard_size_category: "large",
        yard_usability: 5,
        is_fenced: true,
        has_outdoor_space: true,
        vibe: "quiet",
        street_parking_ease: 4,
        commute_weighted_score: null,
        stretch_pct: null,
      },
    },
    {
      address: "501 Roy St #428",
      city: "Seattle",
      state: "WA",
      zipCode: "98109",
      listPrice: 425000,
      propertyType: "CONDO" as const,
      bedrooms: 2,
      bathroomsFull: 1,
      bathroomsHalf: 0,
      interiorSqft: 880,
      lotSqft: null,
      yearBuilt: 2005,
      vector: {
        price: 425000,
        price_per_sqft: 483,
        bedrooms: 2,
        bathrooms: 1,
        interior_sqft: 880,
        lot_sqft: null,
        year_built: 2005,
        walk_score: 96,
        commute_minutes_primary: 10,
        school_rating: 5,
        noise_level: 2,
        street_type: "arterial",
        roof_age_years: null,
        hvac_age_years: null,
        has_solar: false,
        heating_type: "electric",
        openness: 4,
        kitchen_layout: "galley",
        has_dining_room: false,
        home_office_count: 0,
        storage_abundance: 1,
        ceiling_height_feet: 9,
        natural_light: 4,
        view_quality: 4,
        privacy_from_neighbors: 3,
        finish_quality: "high_end",
        move_in_readiness: 5,
        yard_size_category: "none",
        yard_usability: null,
        is_fenced: false,
        has_outdoor_space: false,
        vibe: "lively",
        street_parking_ease: 1,
        commute_weighted_score: null,
        stretch_pct: null,
      },
    },
    {
      address: "3321 Wallingford Ave N",
      city: "Seattle",
      state: "WA",
      zipCode: "98103",
      listPrice: 549000,
      propertyType: "SFH" as const,
      bedrooms: 3,
      bathroomsFull: 1,
      bathroomsHalf: 1,
      interiorSqft: 1480,
      lotSqft: 3900,
      yearBuilt: 1928,
      vector: {
        price: 549000,
        price_per_sqft: 371,
        bedrooms: 3,
        bathrooms: 1.5,
        interior_sqft: 1480,
        lot_sqft: 3900,
        year_built: 1928,
        walk_score: 88,
        commute_minutes_primary: 18,
        school_rating: 7,
        noise_level: 3,
        street_type: "quiet_residential",
        roof_age_years: 15,
        hvac_age_years: 20,
        has_solar: false,
        heating_type: "gas",
        openness: 2,
        kitchen_layout: "galley",
        has_dining_room: true,
        home_office_count: 0,
        storage_abundance: 2,
        ceiling_height_feet: 8.5,
        natural_light: 3,
        view_quality: 1,
        privacy_from_neighbors: 2,
        finish_quality: "builder_grade",
        move_in_readiness: 2,
        yard_size_category: "small",
        yard_usability: 3,
        is_fenced: false,
        has_outdoor_space: true,
        vibe: "established",
        street_parking_ease: 3,
        commute_weighted_score: null,
        stretch_pct: null,
      },
    },
    {
      address: "10456 Meridian Ave N",
      city: "Seattle",
      state: "WA",
      zipCode: "98133",
      listPrice: 475000,
      propertyType: "SFH" as const,
      bedrooms: 3,
      bathroomsFull: 2,
      bathroomsHalf: 0,
      interiorSqft: 1560,
      lotSqft: 5400,
      yearBuilt: 1965,
      vector: {
        price: 475000,
        price_per_sqft: 305,
        bedrooms: 3,
        bathrooms: 2,
        interior_sqft: 1560,
        lot_sqft: 5400,
        year_built: 1965,
        walk_score: 62,
        commute_minutes_primary: 32,
        school_rating: 6,
        noise_level: 4,
        street_type: "quiet_residential",
        roof_age_years: 10,
        hvac_age_years: 8,
        has_solar: false,
        heating_type: "gas",
        openness: 3,
        kitchen_layout: "l_shape",
        has_dining_room: true,
        home_office_count: 1,
        storage_abundance: 4,
        ceiling_height_feet: 8,
        natural_light: 3,
        view_quality: 2,
        privacy_from_neighbors: 4,
        finish_quality: "mid",
        move_in_readiness: 4,
        yard_size_category: "medium",
        yard_usability: 4,
        is_fenced: true,
        has_outdoor_space: true,
        vibe: "sleepy",
        street_parking_ease: 5,
        commute_weighted_score: null,
        stretch_pct: null,
      },
    },
    {
      address: "2200 Westlake Ave #1205",
      city: "Seattle",
      state: "WA",
      zipCode: "98121",
      listPrice: 520000,
      propertyType: "CONDO" as const,
      bedrooms: 2,
      bathroomsFull: 2,
      bathroomsHalf: 0,
      interiorSqft: 1050,
      lotSqft: null,
      yearBuilt: 2019,
      vector: {
        price: 520000,
        price_per_sqft: 495,
        bedrooms: 2,
        bathrooms: 2,
        interior_sqft: 1050,
        lot_sqft: null,
        year_built: 2019,
        walk_score: 98,
        commute_minutes_primary: 8,
        school_rating: 4,
        noise_level: 1,
        street_type: "arterial",
        roof_age_years: null,
        hvac_age_years: null,
        has_solar: false,
        heating_type: "electric",
        openness: 5,
        kitchen_layout: "open_great_room",
        has_dining_room: false,
        home_office_count: 1,
        storage_abundance: 2,
        ceiling_height_feet: 10,
        natural_light: 5,
        view_quality: 5,
        privacy_from_neighbors: 4,
        finish_quality: "luxury",
        move_in_readiness: 5,
        yard_size_category: "none",
        yard_usability: null,
        is_fenced: false,
        has_outdoor_space: true,
        vibe: "lively",
        street_parking_ease: 1,
        commute_weighted_score: null,
        stretch_pct: null,
      },
    },
    {
      address: "4512 Burke Ave N",
      city: "Seattle",
      state: "WA",
      zipCode: "98103",
      listPrice: 610000,
      propertyType: "SFH" as const,
      bedrooms: 4,
      bathroomsFull: 2,
      bathroomsHalf: 1,
      interiorSqft: 1980,
      lotSqft: 4200,
      yearBuilt: 1940,
      yearRenovated: 2020,
      vector: {
        price: 610000,
        price_per_sqft: 308,
        bedrooms: 4,
        bathrooms: 2.5,
        interior_sqft: 1980,
        lot_sqft: 4200,
        year_built: 1940,
        walk_score: 85,
        commute_minutes_primary: 20,
        school_rating: 7,
        noise_level: 4,
        street_type: "quiet_residential",
        roof_age_years: 4,
        hvac_age_years: 4,
        has_solar: false,
        heating_type: "heat_pump",
        openness: 4,
        kitchen_layout: "island",
        has_dining_room: true,
        home_office_count: 2,
        storage_abundance: 3,
        ceiling_height_feet: 9,
        natural_light: 5,
        view_quality: 3,
        privacy_from_neighbors: 3,
        finish_quality: "high_end",
        move_in_readiness: 5,
        yard_size_category: "medium",
        yard_usability: 3,
        is_fenced: true,
        has_outdoor_space: true,
        vibe: "established",
        street_parking_ease: 3,
        commute_weighted_score: null,
        stretch_pct: null,
      },
    },
  ]

  for (const listing of listings) {
    await prisma.listing.create({
      data: {
        agentId: agent.id,
        ...listing,
      },
    })
  }

  console.log(`  ✓ Created ${listings.length} listings`)
  console.log("\n✅ Seed complete!")
  console.log(`\n  Agent login: http://localhost:3000/agent?as=${agent.id}`)
  console.log(`  Buyer 1 login: http://localhost:3000/buyer?as=${buyer1.id}`)
  console.log(`  Buyer 2 login: http://localhost:3000/buyer?as=${buyer2.id}`)
}

main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })
