import { PrismaClient } from "@prisma/client"

const prisma = new PrismaClient()

async function main() {
  console.log("🌱 Seeding database (Massachusetts)...")

  // Clear existing data
  await prisma.listing.deleteMany()
  await prisma.buyerProfile.deleteMany()
  await prisma.user.deleteMany()

  // --- Agent ---
  const agent = await prisma.user.create({
    data: {
      email: "agent@homematch.dev",
      name: "Victor (Agent)",
      role: "AGENT",
      phone: "617-555-0001",
    },
  })
  console.log(`  ✓ Agent: ${agent.name} (${agent.id})`)

  // --- Buyers ---
  const buyer1 = await prisma.user.create({
    data: {
      email: "buyer1@homematch.dev",
      name: "Sarah Chen",
      role: "BUYER",
      phone: "617-555-0002",
    },
  })

  const buyer2 = await prisma.user.create({
    data: {
      email: "buyer2@homematch.dev",
      name: "Marcus Johnson",
      role: "BUYER",
      phone: "617-555-0003",
    },
  })

  // --- Buyer Profiles (MA focused) ---
  const bp1 = await prisma.buyerProfile.create({
    data: {
      userId: buyer1.id,
      agentId: agent.id,
      status: "ACTIVE",
      budgetMin: 550000,
      budgetMax: 850000,
      minBedrooms: 3,
      minBathrooms: 2,
      propertyTypes: ["SFH", "TOWNHOUSE"],
      targetCities: ["Newton", "Brookline", "Wellesley"],
      targetZipCodes: ["02458", "02459", "02445", "02446", "02481"],
      mustHaves: ["natural_light", "home_office_count"],
      dealBreakers: ["noise_level"],
    },
  })

  const bp2 = await prisma.buyerProfile.create({
    data: {
      userId: buyer2.id,
      agentId: agent.id,
      status: "ACTIVE",
      budgetMin: 400000,
      budgetMax: 650000,
      minBedrooms: 2,
      minBathrooms: 1,
      propertyTypes: ["CONDO", "TOWNHOUSE"],
      targetCities: ["Cambridge", "Somerville", "Boston"],
      targetZipCodes: ["02139", "02140", "02144", "02116", "02118"],
      mustHaves: ["walk_score", "commute_minutes_primary"],
      dealBreakers: [],
    },
  })

  console.log(`  ✓ Buyer: ${buyer1.name} (${bp1.id})`)
  console.log(`  ✓ Buyer: ${buyer2.name} (${bp2.id})`)

  // --- Listings (8 MA properties with realistic vectors) ---
  const listings = [
    {
      address: "47 Commonwealth Ave #3",
      city: "Boston",
      state: "MA",
      zipCode: "02116",
      listPrice: 589000,
      propertyType: "CONDO" as const,
      bedrooms: 2,
      bathroomsFull: 1,
      bathroomsHalf: 0,
      interiorSqft: 1050,
      lotSqft: null,
      yearBuilt: 1890,
      yearRenovated: 2019,
      vector: {
        price: 589000,
        price_per_sqft: 561,
        bedrooms: 2,
        bathrooms: 1,
        interior_sqft: 1050,
        lot_sqft: null,
        year_built: 1890,
        walk_score: 97,
        commute_minutes_primary: 12,
        school_rating: 6,
        noise_level: 2,
        street_type: "busy_residential",
        roof_age_years: null,
        hvac_age_years: 5,
        has_solar: false,
        heating_type: "gas",
        openness: 3,
        kitchen_layout: "galley",
        has_dining_room: true,
        home_office_count: 0,
        storage_abundance: 2,
        ceiling_height_feet: 10,
        natural_light: 4,
        view_quality: 3,
        privacy_from_neighbors: 2,
        finish_quality: "high_end",
        move_in_readiness: 5,
        yard_size_category: "none",
        yard_usability: null,
        is_fenced: false,
        has_outdoor_space: false,
        vibe: "lively",
        street_parking_ease: 1,
        commute_weighted_score: null,
        stretch_pct: null,
      },
    },
    {
      address: "238 Brattle St",
      city: "Cambridge",
      state: "MA",
      zipCode: "02138",
      listPrice: 1250000,
      propertyType: "SFH" as const,
      bedrooms: 4,
      bathroomsFull: 3,
      bathroomsHalf: 1,
      interiorSqft: 2800,
      lotSqft: 8500,
      yearBuilt: 1920,
      yearRenovated: 2021,
      vector: {
        price: 1250000,
        price_per_sqft: 446,
        bedrooms: 4,
        bathrooms: 3.5,
        interior_sqft: 2800,
        lot_sqft: 8500,
        year_built: 1920,
        walk_score: 78,
        commute_minutes_primary: 18,
        school_rating: 9,
        noise_level: 4,
        street_type: "quiet_residential",
        roof_age_years: 5,
        hvac_age_years: 3,
        has_solar: true,
        heating_type: "heat_pump",
        openness: 4,
        kitchen_layout: "island",
        has_dining_room: true,
        home_office_count: 2,
        storage_abundance: 4,
        ceiling_height_feet: 9.5,
        natural_light: 5,
        view_quality: 3,
        privacy_from_neighbors: 4,
        finish_quality: "luxury",
        move_in_readiness: 5,
        yard_size_category: "large",
        yard_usability: 5,
        is_fenced: true,
        has_outdoor_space: true,
        vibe: "established",
        street_parking_ease: 3,
        commute_weighted_score: null,
        stretch_pct: null,
      },
    },
    {
      address: "15 Cypress St #2",
      city: "Brookline",
      state: "MA",
      zipCode: "02445",
      listPrice: 725000,
      propertyType: "CONDO" as const,
      bedrooms: 3,
      bathroomsFull: 2,
      bathroomsHalf: 0,
      interiorSqft: 1450,
      lotSqft: null,
      yearBuilt: 1925,
      yearRenovated: 2018,
      vector: {
        price: 725000,
        price_per_sqft: 500,
        bedrooms: 3,
        bathrooms: 2,
        interior_sqft: 1450,
        lot_sqft: null,
        year_built: 1925,
        walk_score: 89,
        commute_minutes_primary: 20,
        school_rating: 9,
        noise_level: 4,
        street_type: "quiet_residential",
        roof_age_years: null,
        hvac_age_years: 6,
        has_solar: false,
        heating_type: "gas",
        openness: 3,
        kitchen_layout: "l_shape",
        has_dining_room: true,
        home_office_count: 1,
        storage_abundance: 3,
        ceiling_height_feet: 9,
        natural_light: 4,
        view_quality: 2,
        privacy_from_neighbors: 3,
        finish_quality: "high_end",
        move_in_readiness: 4,
        yard_size_category: "small",
        yard_usability: 3,
        is_fenced: false,
        has_outdoor_space: true,
        vibe: "established",
        street_parking_ease: 2,
        commute_weighted_score: null,
        stretch_pct: null,
      },
    },
    {
      address: "82 Highland Ave",
      city: "Somerville",
      state: "MA",
      zipCode: "02143",
      listPrice: 485000,
      propertyType: "CONDO" as const,
      bedrooms: 2,
      bathroomsFull: 1,
      bathroomsHalf: 0,
      interiorSqft: 900,
      lotSqft: null,
      yearBuilt: 1910,
      yearRenovated: 2022,
      vector: {
        price: 485000,
        price_per_sqft: 539,
        bedrooms: 2,
        bathrooms: 1,
        interior_sqft: 900,
        lot_sqft: null,
        year_built: 1910,
        walk_score: 92,
        commute_minutes_primary: 15,
        school_rating: 7,
        noise_level: 3,
        street_type: "busy_residential",
        roof_age_years: null,
        hvac_age_years: 2,
        has_solar: false,
        heating_type: "gas",
        openness: 4,
        kitchen_layout: "open_great_room",
        has_dining_room: false,
        home_office_count: 1,
        storage_abundance: 2,
        ceiling_height_feet: 9,
        natural_light: 5,
        view_quality: 3,
        privacy_from_neighbors: 3,
        finish_quality: "high_end",
        move_in_readiness: 5,
        yard_size_category: "none",
        yard_usability: null,
        is_fenced: false,
        has_outdoor_space: true,
        vibe: "up_and_coming",
        street_parking_ease: 2,
        commute_weighted_score: null,
        stretch_pct: null,
      },
    },
    {
      address: "312 Walnut St",
      city: "Newton",
      state: "MA",
      zipCode: "02460",
      listPrice: 895000,
      propertyType: "SFH" as const,
      bedrooms: 4,
      bathroomsFull: 2,
      bathroomsHalf: 1,
      interiorSqft: 2200,
      lotSqft: 7200,
      yearBuilt: 1955,
      yearRenovated: 2017,
      vector: {
        price: 895000,
        price_per_sqft: 407,
        bedrooms: 4,
        bathrooms: 2.5,
        interior_sqft: 2200,
        lot_sqft: 7200,
        year_built: 1955,
        walk_score: 65,
        commute_minutes_primary: 30,
        school_rating: 10,
        noise_level: 5,
        street_type: "quiet_residential",
        roof_age_years: 7,
        hvac_age_years: 7,
        has_solar: false,
        heating_type: "gas",
        openness: 3,
        kitchen_layout: "u_shape",
        has_dining_room: true,
        home_office_count: 1,
        storage_abundance: 4,
        ceiling_height_feet: 8,
        natural_light: 4,
        view_quality: 2,
        privacy_from_neighbors: 5,
        finish_quality: "mid",
        move_in_readiness: 3,
        yard_size_category: "large",
        yard_usability: 5,
        is_fenced: true,
        has_outdoor_space: true,
        vibe: "quiet",
        street_parking_ease: 5,
        commute_weighted_score: null,
        stretch_pct: null,
      },
    },
    {
      address: "1200 Boylston St #405",
      city: "Boston",
      state: "MA",
      zipCode: "02215",
      listPrice: 620000,
      propertyType: "CONDO" as const,
      bedrooms: 2,
      bathroomsFull: 2,
      bathroomsHalf: 0,
      interiorSqft: 1100,
      lotSqft: null,
      yearBuilt: 2020,
      vector: {
        price: 620000,
        price_per_sqft: 564,
        bedrooms: 2,
        bathrooms: 2,
        interior_sqft: 1100,
        lot_sqft: null,
        year_built: 2020,
        walk_score: 95,
        commute_minutes_primary: 8,
        school_rating: 5,
        noise_level: 1,
        street_type: "arterial",
        roof_age_years: null,
        hvac_age_years: null,
        has_solar: false,
        heating_type: "electric",
        openness: 5,
        kitchen_layout: "open_great_room",
        has_dining_room: false,
        home_office_count: 1,
        storage_abundance: 3,
        ceiling_height_feet: 10,
        natural_light: 5,
        view_quality: 5,
        privacy_from_neighbors: 4,
        finish_quality: "luxury",
        move_in_readiness: 5,
        yard_size_category: "none",
        yard_usability: null,
        is_fenced: false,
        has_outdoor_space: true,
        vibe: "lively",
        street_parking_ease: 1,
        commute_weighted_score: null,
        stretch_pct: null,
      },
    },
    {
      address: "56 Prescott St",
      city: "Cambridge",
      state: "MA",
      zipCode: "02139",
      listPrice: 549000,
      propertyType: "TOWNHOUSE" as const,
      bedrooms: 3,
      bathroomsFull: 1,
      bathroomsHalf: 1,
      interiorSqft: 1350,
      lotSqft: 1800,
      yearBuilt: 1900,
      yearRenovated: 2015,
      vector: {
        price: 549000,
        price_per_sqft: 407,
        bedrooms: 3,
        bathrooms: 1.5,
        interior_sqft: 1350,
        lot_sqft: 1800,
        year_built: 1900,
        walk_score: 94,
        commute_minutes_primary: 12,
        school_rating: 8,
        noise_level: 3,
        street_type: "quiet_residential",
        roof_age_years: 9,
        hvac_age_years: 9,
        has_solar: false,
        heating_type: "gas",
        openness: 2,
        kitchen_layout: "galley",
        has_dining_room: true,
        home_office_count: 0,
        storage_abundance: 2,
        ceiling_height_feet: 8.5,
        natural_light: 3,
        view_quality: 1,
        privacy_from_neighbors: 2,
        finish_quality: "mid",
        move_in_readiness: 3,
        yard_size_category: "small",
        yard_usability: 3,
        is_fenced: true,
        has_outdoor_space: true,
        vibe: "established",
        street_parking_ease: 2,
        commute_weighted_score: null,
        stretch_pct: null,
      },
    },
    {
      address: "189 Crafts St",
      city: "Newton",
      state: "MA",
      zipCode: "02458",
      listPrice: 780000,
      propertyType: "SFH" as const,
      bedrooms: 3,
      bathroomsFull: 2,
      bathroomsHalf: 0,
      interiorSqft: 1800,
      lotSqft: 5500,
      yearBuilt: 1940,
      yearRenovated: 2020,
      vector: {
        price: 780000,
        price_per_sqft: 433,
        bedrooms: 3,
        bathrooms: 2,
        interior_sqft: 1800,
        lot_sqft: 5500,
        year_built: 1940,
        walk_score: 72,
        commute_minutes_primary: 25,
        school_rating: 9,
        noise_level: 4,
        street_type: "quiet_residential",
        roof_age_years: 4,
        hvac_age_years: 4,
        has_solar: false,
        heating_type: "heat_pump",
        openness: 4,
        kitchen_layout: "island",
        has_dining_room: true,
        home_office_count: 2,
        storage_abundance: 3,
        ceiling_height_feet: 9,
        natural_light: 5,
        view_quality: 3,
        privacy_from_neighbors: 4,
        finish_quality: "high_end",
        move_in_readiness: 5,
        yard_size_category: "medium",
        yard_usability: 4,
        is_fenced: true,
        has_outdoor_space: true,
        vibe: "quiet",
        street_parking_ease: 4,
        commute_weighted_score: null,
        stretch_pct: null,
      },
    },
  ]

  for (const listing of listings) {
    await prisma.listing.create({
      data: {
        agentId: agent.id,
        ...listing,
      },
    })
  }

  console.log(`  ✓ Created ${listings.length} listings (MA)`)
  console.log("\n✅ Seed complete!")
  console.log(`\n  Agent login: http://localhost:3000/agent?as=${agent.id}`)
  console.log(`  Buyer 1 login: http://localhost:3000/buyer?as=${buyer1.id}`)
  console.log(`  Buyer 2 login: http://localhost:3000/buyer?as=${buyer2.id}`)
}

main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })
