/**
 * Mock listings for demo — realistic Greater Boston properties.
 * In production, these come from MLS feed or agent input.
 */

import type { ListingForMatch } from "./match-engine"

export const MOCK_LISTINGS: ListingForMatch[] = [
  {
    id: "listing_1",
    address: "47 Mystic St",
    city: "Arlington",
    price: 1150000,
    bedrooms: 4,
    bathrooms: 2.5,
    sqft: 2200,
    yearBuilt: 1928,
    propertyType: "Single Family",
    dimensions: {
      natural_light: 5,
      noise_level: 5,
      openness: 4,
      school_rating: 9,
      walk_score: 72,
      yard_usability: 4,
      move_in_readiness: 4,
      privacy: 4,
      kitchen_quality: 5,
      commute_primary: 22,
      commute_secondary: 28,
      style: "Colonial",
      street_type: "quiet_residential",
    },
    description: "Beautifully renovated 1928 Colonial on a quiet tree-lined street. Chef's kitchen with island (2022 renovation), hardwood floors throughout, south-facing living room floods with afternoon light. Fenced backyard with mature landscaping. Steps to Minuteman Bikeway. Ottoson Middle / Arlington High.",
  },
  {
    id: "listing_2",
    address: "183 Pleasant St",
    city: "Arlington",
    price: 1050000,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1850,
    yearBuilt: 1940,
    propertyType: "Single Family",
    dimensions: {
      natural_light: 4,
      noise_level: 4,
      openness: 3,
      school_rating: 9,
      walk_score: 78,
      yard_usability: 3,
      move_in_readiness: 3,
      privacy: 3,
      kitchen_quality: 3,
      commute_primary: 20,
      commute_secondary: 30,
      style: "Cape Cod",
      street_type: "quiet_residential",
    },
    description: "Classic Cape Cod with expansion potential. 3BR/2BA with unfinished attic that could be a 4th bedroom. Kitchen is functional but original — cosmetic update would transform it. Walk Score 78 — walk to Capitol Theatre and local shops. Great bones, great location, needs some love.",
  },
  {
    id: "listing_3",
    address: "22 Slade St",
    city: "Belmont",
    price: 1280000,
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2450,
    yearBuilt: 1955,
    propertyType: "Single Family",
    dimensions: {
      natural_light: 5,
      noise_level: 5,
      openness: 4,
      school_rating: 9,
      walk_score: 55,
      yard_usability: 5,
      move_in_readiness: 5,
      privacy: 5,
      kitchen_quality: 4,
      commute_primary: 25,
      commute_secondary: 32,
      style: "Colonial",
      street_type: "quiet_residential",
    },
    description: "Stunning renovated Colonial in Belmont Hill. Sun-drenched with floor-to-ceiling windows added in 2019 renovation. Open kitchen/family room, first-floor office, flat half-acre lot with playset. Belmont schools (top 5 in MA). Incredibly quiet — feels like country but 25 min to Kendall.",
  },
  {
    id: "listing_4",
    address: "8 Irma Ave",
    city: "Watertown",
    price: 920000,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1650,
    yearBuilt: 1952,
    propertyType: "Single Family",
    dimensions: {
      natural_light: 3,
      noise_level: 3,
      openness: 3,
      school_rating: 7,
      walk_score: 82,
      yard_usability: 3,
      move_in_readiness: 3,
      privacy: 3,
      kitchen_quality: 2,
      commute_primary: 15,
      commute_secondary: 25,
      style: "Ranch",
      street_type: "busy_residential",
    },
    description: "Solid Ranch on a busier residential street near Watertown Square. Incredible commute to Kendall (15 min). Kitchen original 1990s — functional but dated. Walk Score 82 — grocery, restaurants, everything walkable. Smaller yard. School rating 7/10. Best value in the group if you can handle some noise and a reno.",
  },
  {
    id: "listing_5",
    address: "155 Summer St",
    city: "Arlington",
    price: 1195000,
    bedrooms: 4,
    bathrooms: 2.5,
    sqft: 2100,
    yearBuilt: 1910,
    propertyType: "Single Family",
    dimensions: {
      natural_light: 4,
      noise_level: 4,
      openness: 3,
      school_rating: 9,
      walk_score: 68,
      yard_usability: 4,
      move_in_readiness: 3,
      privacy: 4,
      kitchen_quality: 3,
      commute_primary: 24,
      commute_secondary: 30,
      style: "Craftsman",
      street_type: "quiet_residential",
    },
    description: "Original 1910 Craftsman with incredible woodwork, built-in bookcases, and stained glass accents. 4BR/2.5BA, large lot with fenced yard. Kitchen updated in 2015 (granite + SS) but layout is galley-style. Beautiful home with character — needs someone who appreciates the charm.",
  },
  {
    id: "listing_6",
    address: "34 Bacon St",
    city: "Watertown",
    price: 985000,
    bedrooms: 3,
    bathrooms: 2.5,
    sqft: 1900,
    yearBuilt: 2018,
    propertyType: "Townhouse",
    dimensions: {
      natural_light: 4,
      noise_level: 3,
      openness: 5,
      school_rating: 7,
      walk_score: 85,
      yard_usability: 2,
      move_in_readiness: 5,
      privacy: 2,
      kitchen_quality: 5,
      commute_primary: 12,
      commute_secondary: 22,
      style: "Contemporary",
      street_type: "busy_residential",
    },
    description: "Brand new construction townhouse. Open concept living, chef's kitchen with waterfall island, 9ft ceilings, Central AC. Tiny patio (no real yard). Walk Score 85, 12 min to Kendall. Modern and move-in perfect — but it's a townhouse on a busier street with shared walls.",
  },
]
